sudo: false
language: php
php:
  - 7.1
before_script:
  - composer self-update
  - composer install
script:
  - php vendor/bin/phpunit --coverage-clover=coverage.clover
  - php vendor/bin/phpstan analyse --no-interaction
  - php vendor/bin/psalm
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
